runtime: nodejs
env: flex

service: flex-non-custom

instance_class: F4

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
  target_concurrent_requests: 50

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

liveness_check:
  path: "/"
  check_interval_sec: 60
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
